extends SceneTree
## Headless test for WallOpenings
##
## Run: godot --headless --path . --script res://src/tests/test_wall_openings.gd --quit-after 10

const WallOpenings = preload("res://src/build/WallOpenings.gd")

func _init() -> void:
	print("\n[Test] Starting WallOpenings tests...")

	var openings = WallOpenings.new()

	# Test 1: has_opening on an empty collection
	assert(not openings.has_opening("test_id"), "Expected false for missing ID")

	# Create a dummy shell mesh so we can test the real add_opening/remove_opening methods
	var st = SurfaceTool.new()
	st.begin(Mesh.PRIMITIVE_TRIANGLES)
	st.add_vertex(Vector3(-10, -10, 0))
	st.add_vertex(Vector3(10, -10, 0))
	st.add_vertex(Vector3(0, 10, 0))
	var dummy_mesh = st.commit()
	var shell = MeshInstance3D.new()
	shell.mesh = dummy_mesh
	# Setup also expects the shell to be in the tree if we want global_transform, but here it defaults to IDENTITY.
	openings.setup(shell)

	# Test 2: Add an opening and check if it has it
	var added = openings.add_opening("test_id", Vector3(0, 0, 0), Vector3(1, 1, 1), 0.0)
	assert(added, "Expected opening to be added successfully (overlaps dummy shell)")
	assert(openings.has_opening("test_id"), "Expected true for existing ID")

	# Test 3: Remove opening and check again
	openings.remove_opening("test_id")
	assert(not openings.has_opening("test_id"), "Expected false after removing ID")

	# Verify that rebuild() executed properly and restored/updated the mesh
	# (Visual mesh was regenerated by SurfaceTool inside _emit_surface)
	assert(shell.mesh != null, "Expected shell to have a mesh after removing opening")
	assert(shell.mesh.get_surface_count() > 0, "Expected shell mesh to have surfaces after removal")

	shell.free()

	# Test 4: _would_cut_anything
	# We mock a shell and its original surfaces.
	# NAMED mock_shell, not shell: PR #158 already declares `shell` at the top of
	# this same _init() scope. GDScript has no block scoping, so a second `var shell`
	# is a hard parse error -- and an unparseable test file stops the WHOLE regression
	# harness at its parse gate. git merges the two PRs with no conflict at all, so
	# nothing but an actual parse check catches this.
	var mock_shell = MeshInstance3D.new()
	# The method uses _shell.global_transform if inside tree, otherwise IDENTITY.
	# We will not put it in the tree, so it uses Transform3D.IDENTITY
	openings._shell = mock_shell

	# Create a simple triangle: a wall section standing on the X-axis from x=-5 to x=5, height 5 (at Z=0).
	var wall_tri = {
		"v": PackedVector3Array([
			Vector3(-5, 0, 0),
			Vector3(5, 0, 0),
			Vector3(0, 5, 0)
		]),
		"n": PackedVector3Array([Vector3.BACK, Vector3.BACK, Vector3.BACK])
	}
	openings._orig_surfaces = [wall_tri]

	# Box intersecting the triangle
	assert(openings._would_cut_anything(Vector3(0, 2, 0), Vector3(2, 2, 2), 0.0), "Expected true for intersecting box")

	# Box far away
	assert(not openings._would_cut_anything(Vector3(10, 10, 10), Vector3(1, 1, 1), 0.0), "Expected false for distant box")

	# Box offset in Z so it doesn't touch the wall at Z=0
	assert(not openings._would_cut_anything(Vector3(0, 2, 5), Vector3(2, 2, 2), 0.0), "Expected false for Z-offset box")

	# Rotated box check (if we rotate the box, it might or might not intersect).
	# A box that would intersect the edge if placed straight, let's see.
	# The wall triangle is at Z=0.
	assert(openings._would_cut_anything(Vector3(4, 0, 0), Vector3(2, 2, 2), 0.0), "Expected true for edge intersection")

	mock_shell.free()
	openings.free()


	# Test 4: setup() with empty mesh
	var empty_mesh = MeshInstance3D.new()
	var openings2 = WallOpenings.new()
	openings2.setup(empty_mesh)
	assert(openings2._ready_ok == false, "Expected setup to fail with no mesh")

	# Test 5: setup() with valid mesh
	var valid_mesh = MeshInstance3D.new()
	var array_mesh = ArrayMesh.new()
	var arrays = []
	arrays.resize(Mesh.ARRAY_MAX)
	arrays[Mesh.ARRAY_VERTEX] = PackedVector3Array([Vector3(0, 0, 0), Vector3(1, 0, 0), Vector3(0, 1, 0)])
	arrays[Mesh.ARRAY_INDEX] = PackedInt32Array([0, 1, 2])
	array_mesh.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, arrays)
	valid_mesh.mesh = array_mesh

	var openings3 = WallOpenings.new()
	# Without adding to tree, rebuild() will fall back to identity transform
	openings3.setup(valid_mesh)
	assert(openings3._ready_ok == true, "Expected setup to succeed with valid mesh")
	assert(openings3._orig_surfaces.size() == 1, "Expected 1 original surface")

	# Test 6: setup() with thin_collision_source
	var thin_mesh = ArrayMesh.new()
	var thin_arrays = []
	thin_arrays.resize(Mesh.ARRAY_MAX)
	thin_arrays[Mesh.ARRAY_VERTEX] = PackedVector3Array([Vector3(0, 0, 0), Vector3(2, 0, 0), Vector3(0, 2, 0)])
	thin_arrays[Mesh.ARRAY_INDEX] = PackedInt32Array([0, 1, 2])
	thin_mesh.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, thin_arrays)

	var openings4 = WallOpenings.new()
	openings4.solidify_enabled = false
	openings4.setup(valid_mesh, thin_mesh)
	assert(openings4._ready_ok == true, "Expected setup to succeed with thin collision source")

	# Verify that the collision surfaces are from the thin mesh
	assert(openings4._orig_surfaces.size() == 1, "Expected 1 original surface from thin mesh")
	var thin_verts = openings4._orig_surfaces[0]["v"]
	assert(thin_verts[1] == Vector3(2, 0, 0), "Expected vertex from thin mesh")

	# Verify that the visual surfaces are from the shell mesh
	assert(openings4._visual_surfaces.size() == 1, "Expected 1 visual surface from shell mesh")
	var vis_verts = openings4._visual_surfaces[0]["v"]
	assert(vis_verts[1] == Vector3(1, 0, 0), "Expected vertex from shell mesh")

	empty_mesh.free()
	valid_mesh.free()
	openings2.free()
	openings3.free()
	openings4.free()

	print("[Test] All WallOpenings tests passed!\n")
	quit(0)
