extends SceneTree
## Headless test for WallOpenings
##
## Run: godot --headless --path . --script res://src/tests/test_wall_openings.gd --quit-after 10

const WallOpenings = preload("res://src/build/WallOpenings.gd")

func _init() -> void:
	print("\n[Test] Starting WallOpenings tests...")

	var openings = WallOpenings.new()

	# Test 1: has_opening on an empty collection
	assert(not openings.has_opening("test_id"), "Expected false for missing ID")

	# Create a dummy shell mesh so we can test the real add_opening/remove_opening methods
	var st = SurfaceTool.new()
	st.begin(Mesh.PRIMITIVE_TRIANGLES)
	st.add_vertex(Vector3(-10, -10, 0))
	st.add_vertex(Vector3(10, -10, 0))
	st.add_vertex(Vector3(0, 10, 0))
	var dummy_mesh = st.commit()
	var shell = MeshInstance3D.new()
	shell.mesh = dummy_mesh
	# Setup also expects the shell to be in the tree if we want global_transform, but here it defaults to IDENTITY.
	openings.setup(shell)

	# Test 2: Add an opening and check if it has it
	var added = openings.add_opening("test_id", Vector3(0, 0, 0), Vector3(1, 1, 1), 0.0)
	assert(added, "Expected opening to be added successfully (overlaps dummy shell)")
	assert(openings.has_opening("test_id"), "Expected true for existing ID")

	# Test 3: Remove opening and check again
	openings.remove_opening("test_id")
	assert(not openings.has_opening("test_id"), "Expected false after removing ID")

	# Verify that rebuild() executed properly and restored/updated the mesh
	# (Visual mesh was regenerated by SurfaceTool inside _emit_surface)
	assert(shell.mesh != null, "Expected shell to have a mesh after removing opening")
	assert(shell.mesh.get_surface_count() > 0, "Expected shell mesh to have surfaces after removal")

	shell.free()

	openings.free()

	print("[Test] All WallOpenings tests passed!\n")
	quit(0)
