extends Node3D

class_name BuildingShellLoader

# =============================================================================
# #195 — Building shell loader extracted from MainWorld.gd.
# =============================================================================
# Owns the building-shell visual mesh swap (thin .obj → solid .res when present)
# plus the WallOpenings spawn that carves doors / windows / gates at runtime.
# MainWorld instantiates one of these as a child node and calls
# load_shell_and_openings() exactly once during world setup; the loader then
# materialises the visual swap + collision regen via WallOpenings.
#
# Spawned nodes (WallOpenings) are still parented under MainWorld (not under
# this loader), so the resulting scene tree shape is identical to the
# pre-extract layout. The freshly-created WallOpenings instance is also
# written back to `_world.wall_openings` because BuildMode reads it from
# MainWorld a few hundred lines later.

# Reference back to MainWorld for _shell() / _generate_floor_from_shell() / the
# `building_shell_path` export and the `wall_openings` instance var. Set when
# the loader is added to the tree (its parent IS MainWorld), and re-set
# defensively in load_shell_and_openings() in case setup() ran before _ready.
var _world : Node = null
var _building_shell_path : String = ""

func _ready() -> void:
	if _world == null:
		_world = get_parent()

# ── Public entry point ──────────────────────────────────────────────────────
func setup(world: Node, building_shell_path: String) -> void:
	_world = world
	_building_shell_path = building_shell_path

func load_shell_and_openings() -> void:
	if _world == null:
		_world = get_parent()
	_load_building_shell()
	_spawn_wall_openings()

# =============================================================================
# BUILDING SHELL
# =============================================================================
func _load_building_shell() -> void:
	var mesh_instance := _world._shell() as MeshInstance3D
	if not mesh_instance:
		push_error("[BuildingShellLoader] ShellMesh not found")
		return
	# Use the SOLIDIFIED shell (real wall thickness, welded, closed seams) when it
	# exists — kills the zero-thickness light leaks. Built by tools/solidify_building.gd;
	# falls back to the raw thin shell if absent.
	# #105 — collision must come from the THIN mesh, NOT the solid. The solid has
	# 0.30 m wall thickness baked in (inner + outer surfaces), which traps the
	# player capsule between the two faces ("stuck in wall on un-modified walls").
	# WallOpenings does its own collision regen, sourced from a separate thin
	# mesh below; we DON'T call create_trimesh_collision() here anymore so we
	# don't add a thick collider that WallOpenings then has to fight.
	if ResourceLoader.exists("res://assets/models/CeDo_building_solid.res"):
		var solid = load("res://assets/models/CeDo_building_solid.res")
		if solid is Mesh:
			mesh_instance.mesh = solid
			print("[BuildingShellLoader] Using solidified building shell (visual)")
	print("[BuildingShellLoader] Building collision will be generated by WallOpenings (thin mesh)")
	_world._generate_floor_from_shell(mesh_instance)
	print("[BuildingShellLoader] Dynamic floor generated from building corners")

# Caches the building mesh so doors/windows can carve real, walkable openings
# at runtime (never touches the source .obj). Must exist BEFORE BuildMode loads
# its layout, since saved doors/windows re-cut their holes on load.
func _spawn_wall_openings() -> void:
	var shell := _world._shell() as MeshInstance3D
	if not shell:
		push_error("[BuildingShellLoader] ShellMesh not found — wall openings disabled")
		return
	var wall_openings = WallOpenings.new()
	wall_openings.name = "WallOpenings"
	# #105 — when the visible shell is the pre-solid .res, load the THIN .obj
	# separately and hand it to WallOpenings as the COLLISION source. The thin
	# mesh has single-face walls so the player capsule can't wedge between an
	# inner and outer surface, and the WallOpenings carve still drops walkable
	# holes through the thin collision when gates / doors / windows are placed.
	# Visual stays solid for no-light-leak.
	var thin_source : Mesh = null
	if ResourceLoader.exists("res://assets/models/CeDo_building_solid.res"):
		# Disable WallOpenings's own solidify — the visible shell is already thick.
		wall_openings.solidify_enabled = false
		thin_source = load(_building_shell_path) as Mesh
		if thin_source != null:
			print("[BuildingShellLoader] Pre-solid shell active; using thin .obj for collision")
		else:
			push_warning("[BuildingShellLoader] Thin .obj source not loaded; collision will be from solid mesh")
	_world.add_child(wall_openings)
	wall_openings.setup(shell, thin_source)
	# BuildMode reads `wall_openings` off MainWorld later (line ~1246), so keep
	# the reference live on the parent. Forwarder for the extraction.
	_world.wall_openings = wall_openings
	print("[BuildingShellLoader] WallOpenings ready")
